### ISSUE TITLE
Add support for Questionnaire.item.answerOption.coding

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#17]
See possible implementation here: https://github.com/JohannesOehm/compass-numapp-frontend/commit/eead42f076e1d1021b24ef6296ec84c7e8c0e53e

For some reason, I can't create a pull request. Possibly, due to the fact that the other pull request is still open.

**Comment by mbastian93** [comment]
Should be implemented with https://github.com/NUMde/compass-numapp-frontend/commit/14711cc2a7ed6b1d774aff952e2dc725c4757d16
