### ISSUE TITLE
Unterstützung für http://hl7.org/fhir/R4/extension-questionnaire-hidden.html

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#2]
Mit dieser Extension ist es möglich, Elemente aus dem Questionnaire für den Nutzer zu verstecken. 

Hintergrund: Dieses ist eine übliche Option in gängigen EDC-Systemen. Dies kann in einer Vielzahl von Szenarien nützlich sein:

* Informationen, die nicht den Nutzer direkt gefragt werden, sondern anderswo im Code bereitgestellt werden (z.B. per Bluetooth-Verbindung über Wearables oder Meta-Informationen wie die benötigte Zeit zum Ausfüllen), können so im "eigentlichen" Questionnaire untergebracht werden.
* Im Entwicklungsprozess des Formulares können verschiedene Varianten eines Formulares getestet werden
* Abwärtskompatibiltät zu älteren Versionen des Fragebogens kann gewahrt werden, wenn Elemente entfernt werden.

**Comment by mahvaezi** [comment]
Solution commited in #29
