### ISSUE TITLE
Incorrect FHIR implementation of multiple-choice (checkbox) questions

### ISSUE THREAD

**Issue by jonathan-reisdorf** [NUMde/compass-numapp-frontend#23]
**Describe the bug**
In FHIR questionnaires, questions that support more than one answer need to be marked with `"repeats": true`.
Currently, the differentiation between radio button questions vs. checkbox questions is done by using either the `choice` or `open-choice` type, but the latter is meant for a different use case:
Like with `choice` questions, for `open-choice` there is a fixed list of possible answer options, but additionally a free-text field is supposed to be provided. (That is what distinguishes it from `choice` questions)

**Expected behavior**
The backend does not send questionnaires with items of type `open-choice`, but instead with type `choice` and sends an additional property `"repeats": true`. The frontend distinguishes radio button questions (single-choice) vs. checkbox (multiple-choice) by looking at the `repeats` property. If it is absent or `false`, radio buttons are rendered for `choice` questions.

**Additional context**

https://www.hl7.org/fhir/codesystem-item-type.html#item-type-open-choice

https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.repeats

**Comment by GolexPrime** [comment]
Could someone please have a look at the changes made in [update-open-choice](https://github.com/NUMde/compass-numapp-frontend/tree/update-open-choice)? The repeats property should be supported now by choices as well as open-choices. The latter now comes with its own additional text-input element.

**Comment by GolexPrime** [comment]
Should be addressed with 1fb3f56f3b1d2268e08d3f24f1afba069bdc05f9
