### ISSUE TITLE
Support for questionnaire-item-control = "radio-button" oder "drop-down"

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#3]
The Extension http://hl7.org/fhir/R4/extension-questionnaire-itemcontrol.html allows for choice-types the choosing between radio-buttons and drop-down menus. Currently, the app uses always radio-buttons if there is a 

Even though it allows not for new use-cases, this is a common option in most EDC systems, as depending of the length of the questionnaire and the length of the list of choices, drop-down menus can be more clear.

**Comment by mbastian93** [comment]
See possible implementation in branch "extend-extension-support"

**Comment by mbastian93** [comment]
Should be implemented with https://github.com/NUMde/compass-numapp-frontend/commit/301d57506c307d7f3ca207680b2b31a4545b730e. As radio buttons are the default, only the drop-down extension was explicitly considered
