### ISSUE TITLE
enableWhen state should be inherited to childs of item

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#39]
**Describe the bug**
The FHIR specification  states that "When an item is disabled, all of its descendants are disabled, regardless of what their own enableWhen logic might evaluate to." (https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.enableWhen) 

However, it seems that the child items are ignoring this expression and are shown eben if the parent group is disabled.

**To Reproduce**
1. Load the GECCO Reference Questionnaire into the app
2. Open the "Anamnese" Formular 
3. Set "Chronische Lungenerkrankung" to "No"
4. Questions for every possible lung disease are shown nevertheless on the next page

**Expected behavior**
Next page is skipped since all questions are disabled by parent group's enableWhen attribute.

**Smartphone (please complete the following information):**
- iOS 11, Emulator

**Comment by mahvaezi** [comment]
I was going to fix this and saw that the question 1.2 from GECCO Reference Questionnaire is invisible even when the enable when condition for this question is true.

**Comment by mahvaezi** [comment]
solved in #41
