### ISSUE TITLE
Dependency '@react-native-community/async-storage' is deprecated

### ISSUE THREAD

**Issue by mbastian93** [NUMde/compass-numapp-frontend#45]
As stated [here](https://www.npmjs.com/package/@react-native-community/async-storage), '@react-native-community/async-storage' moved to a new organization, therefore the dependency must be updated in package.json

**Comment by GolexPrime** [comment]
It might me worth to think about another option that is also recommended by RN:
https://github.com/emeraldsanto/react-native-encrypted-storage

**Comment by mbastian93** [comment]
> It might me worth to think about another option that is also recommended by RN:
> https://github.com/emeraldsanto/react-native-encrypted-storage

That's a good idea. I'll delete the current pull request and open a new one.
