### ISSUE TITLE
Slider value gets "forgotten" in UI

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#6]
**Describe the bug**

**To Reproduce**
1. Open the first group of the default questionnaire
2. Navigate the questionnaire modal pages using the arrows until you see the slider 
3. Drag the slider in any direction but the middle.
4. Click on the arrow in any direction or the ☑️-button.
5. Navigate back, see that the value you just entered using the slider is lost. The slider is again in "middle position".

**Expected behavior**
The previously entered value is still set in the slider.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 (Simulator)
 - OS: iOS

**Additional context**

**Comment by GolexPrime** [comment]
Good catch!
Should work now correctly with 51c2d58effa20fd36dd487e4bb9af13254d34fbd
