### ISSUE TITLE
Current questionnaire is always marked as 'obsolete'

### ISSUE THREAD

**Issue by mbastian93** [NUMde/compass-numapp-frontend#73]
**Describe the bug**
Every time a 'user update' is triggered when there is already a questionnaire present, the user is informed that this one is obsolete, even though the new one is exactly the same as the current one.

**To Reproduce**
1. Open app
2. When questionnaire is available: repeatedly hit the 'refresh' button
3. Each time user is informed, that the current questionnaire would be 'obsolete'

**Expected behavior**
An update should only happen, when the currently persisted questionnaire definitely differs from the one to be fetched from the backend.

**Screenshots**
 -/-

**Smartphone (please complete the following information):**
 any device

**Additional context**
 -/-

**Comment by mbastian93** [comment]
@GolexPrime @mahvaezi Any thoughts on this?

**Comment by GolexPrime** [comment]
I think your proposal to just assign the ID from the backend seems likes the best and simplest solution.
Using any kind of constructed identifier needs to be coordinated with the adjacent projects - I think that might be an unnecessary effort right now 😅

**Comment by GolexPrime** [comment]
This was addressed (I hope) with #79
