### ISSUE TITLE
Property name "study_id" is misleading

### ISSUE THREAD

**Issue by alena456** [NUMde/compass-numapp-frontend#9]
This issue results from the corresponding [numapp-backend issue](https://github.com/NUMde/compass-numapp-backend/issues/5) which requires an adaptation of the frontend code.

**Comment by alena456** [comment]
@GolexPrime Should we rename "userId" to "subjectId" in order to be consistent with the new name in the backend?

**Comment by GolexPrime** [comment]
> @GolexPrime Should we rename "userId" to "subjectId" in order to be consistent with the new name in the backend?

Sure - as soon as all concerned parties have agreed on an acceptable name :D
It just takes a simple replacement-operation in the frontend - so it's a quick fix.

**Comment by alena456** [comment]
https://github.com/NUMde/compass-numapp-frontend/tree/studyId_fix

**Comment by GolexPrime** [comment]
> I just pushed the necessary changes. I updated all user references to "participant". "Subject" by itself would be too generic and "participant" matches the new route of the backend. Once we have a test instance of the backend running which uses the new route etc. we can check that no mention in the app was missed.

There were a few instances of slightly broken markup in that branch - nothing wild. I incorporated most of the changes made by @alena456 into 2df52b6:
* Every occurrence of "study_id" is being renamed into "subjectId" 
* The user-object in the frontend will keep the name "user" (it's good practice in mobile app development to manage an user-object)
